### ISSUE TITLE
Extension to other Xilinx FPGA device

### ISSUE THREAD

**Issue by lesliepy99** [zslwyuan/AMF-Placer#8]
Hi. I'm now working on a project and want to extend AMF-Placer to another FPGA device (namely, ZCU104), I'm wondering where should I get the device layout of ZCU104(or other device) such that I can modify the parser and extract the device location?
Thanks a lot!

**Comment by zslwyuan** [comment]
Hi @lesliepy99 ,
Yes you can and the steps are provided here: https://zslwyuan.github.io/AMF-Placer/md_doc_pages__2_5__extract_device_informationfrom_vivado.html

**Comment by lesliepy99** [comment]
Hello @zslwyuan, I mean I want to try on another device instead of VCU108, and when I viewing the code in [this file](https://github.com/zslwyuan/AMF-Placer/blob/main/benchmarks/VCU108/preprocessPython/exportDeviceLocation.py), it seems that you first get the X and Y for each site, then infer the exact centric location of each BEL by some rule, what I really want to know is how to design such rule.
Thanks!

**Comment by zslwyuan** [comment]
> Hello @zslwyuan, I mean I want to try on another device instead of VCU108, and when I viewing the code in [this file](https://github.com/zslwyuan/AMF-Placer/blob/main/benchmarks/VCU108/preprocessPython/exportDeviceLocation.py), it seems that you first get the X and Y for each site, then infer the exact centric location of each BEL by some rule, what I really want to know is how to design such rule. Thanks!

Actually, we infer the exact location via the Vivado Device View, where the device is visualized. When a device is visualized in Vivado, you can roughly get the location of each site. However, the distance between two visualized sites is not exactly the physical distance so we have a parameter "y2xratio" in the configuration file to tune the relative ratio of the distance between X/Y directions. ^_^

**Comment by zslwyuan** [comment]
we try several values for "y2xratio" to see which one can generate placement close to the one of Vivado. And we found that "0.4" is a good value for Ultrascale devices.

**Comment by lesliepy99** [comment]
Thanks a lot!
